filter:
  excluded_paths:
  - sdk/php/tests/
  dependency_paths:
  - vendor/

checks:
  php:
    code_rating: true
    duplication: true

build_failure_conditions:
- 'elements.rating(<= D).exists'

build:
  environment:
    mysql: false
    postgresql: false
    mongodb: false
    elasticsearch: false
    redis: false
    memcached: false
    neo4j: false
    rabbitmq: false

  dependencies:
    override:
    - composer update --no-interaction

  nodes:
    analysis:
      tests:
        override:
        - php-scrutinizer-run --enable-security-analysis
