version: '3.2'

volumes:
  node-data:

services:
  node:
    image: node:14-alpine
    environment:
      HOME: /tmp
      PS1: '\[\033[1;32m\]\[\033[1;36m\][\u@\h] \[\033[1;34m\]\w\[\033[0;35m\] \[\033[1;36m\]# \[\033[0m\]'
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ../:/specs:cached
      - node-data:/tmp:cached
    working_dir: /specs/__tests__
